name = "Image Classification Web App"
version = "0.1.0"
description = "A web application that allows users to upload an image and see the classification results."

[[principles]]
    principle = "Simplicity"
    description = "The user interface should be simple and intuitive. The core functionality should be easy to use and understand."

[[principles]]
    principle = "Accuracy"
    description = "The image classification results should be as accurate as possible."

[[principles]]
    principle = "Performance"
    description = "The application should be responsive and provide a smooth user experience."