name = "Image Classification Web App"

[[features]]
    name = "Image Upload"
    description = "Users can upload an image from their local machine."
    requirements = [
        "Support for common image formats (PNG, JPG, etc.).",
        "Display a preview of the uploaded image.",
        "Provide feedback during the upload process (e.g., a loading indicator).",
    ]

[[features]]
    name = "Image Classification"
    description = "The application classifies the content of the uploaded image."
    requirements = [
        "Use a pre-trained model for image classification.",
        "Display the top 5 classification results with their confidence scores.",
        "The classification process should be initiated by a user action (e.g., clicking a button).",
    ]

[[features]]
    name = "User Interface"
    description = "A clean and user-friendly interface."
    requirements = [
        "A clear and descriptive title for the application.",
        "A dedicated area to display the uploaded image.",
        "A section to show the classification results.",
        "Buttons for selecting an image and starting the classification.",
    ]