name = "Image Classification Web App Checklist"

[[sections]]
    name = "Frontend"
    items = [
        { item = "HTML structure is complete and semantic.", checked = false },
        { item = "CSS styles match the design.", checked = false },
        { item = "Image upload is functional.", checked = false },
        { item = "Uploaded image is displayed correctly.", checked = false },
        { item = "UI is responsive.", checked = false },
    ]

[[sections]]
    name = "Backend"
    items = [
        { item = "Web server is running.", checked = false },
        { item = "Image classification model is loaded.", checked = false },
        { item = "API endpoint for classification is working.", checked = false },
        { item = "API handles image data correctly.", checked = false },
        { item = "API returns results in the correct format.", checked = false },
    ]

[[sections]]
    name = "Integration"
    items = [
        { item = "Frontend successfully communicates with the backend API.", checked = false },
        { item = "Classification results are displayed correctly in the UI.", checked = false },
        { item = "Error handling is implemented for API calls.", checked = false },
        { item = "The application is deployed and accessible.", checked = false },
    ]