name = "Image Classification Web App Tasks"

[[tasks]]
    id = "FE-001"
    name = "Create HTML structure"
    description = "Create the basic HTML structure for the web page, including the title, image container, results container, and buttons."
    phase = "Phase 1: Frontend Development"
    status = "To Do"

[[tasks]]
    id = "FE-002"
    name = "Style the UI"
    description = "Style the user interface using CSS to match the provided design."
    phase = "Phase 1: Frontend Development"
    status = "To Do"

[[tasks]]
    id = "FE-003"
    name = "Implement image upload"
    description = "Implement the functionality to allow users to select and upload an image file."
    phase = "Phase 1: Frontend Development"
    status = "To Do"

[[tasks]]
    id = "BE-001"
    name = "Set up web server"
    description = "Set up a simple web server using Python (Flask) or Node.js (Express)."
    phase = "Phase 2: Backend Development"
    status = "To Do"

[[tasks]]
    id = "BE-002"
    name = "Integrate classification model"
    description = "Load a pre-trained image classification model like MobileNetV2."
    phase = "Phase 2: Backend Development"
    status = "To Do"

[[tasks]]
    id = "BE-003"
    name = "Create classification API"
    description = "Create an API endpoint that accepts an image and returns the classification results in JSON format."
    phase = "Phase 2: Backend Development"
    status = "To Do"

[[tasks]]
    id = "INT-001"
    name = "Connect frontend to backend"
    description = "Use JavaScript to send the uploaded image to the backend API and display the results."
    phase = "Phase 3: Integration and Testing"
    status = "To Do"

[[tasks]]
    id = "INT-002"
    name = "End-to-end testing"
    description = "Thoroughly test the application from image upload to result display."
    phase = "Phase 3: Integration and Testing"
    status = "To Do"